# Generated by Django 4.1 on 2023-09-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("practest", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="hobbies",
        ),
        migrations.DeleteModel(
            name="Hobby",
        ),
        migrations.AddField(
            model_name="person",
            name="hobbies",
            field=models.TextField(blank=True, default="{}", null=True),
        ),
    ]
